"""Remove S3Type field from EmailAttachment.

Revision ID: 2d8ec43164c7
Revises: bdd4bf1897cb
Create Date: 2025-12-30 09:54:58.318651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d8ec43164c7'
down_revision: Union[str, Sequence[str], None] = 'bdd4bf1897cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_attachment', 's3_type')
    sa.Enum('AMAZON_S3', 'ALIYUN_OSS', name='s3typeenum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('AMAZON_S3', 'ALIYUN_OSS', name='s3typeenum').create(op.get_bind())
    op.add_column('email_attachment', sa.Column('s3_type', postgresql.ENUM('AMAZON_S3', 'ALIYUN_OSS', name='s3typeenum', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
