"""Add EmailAttachment migration.

Revision ID: 3753f5789fc5
Revises: 7b5ca7b8d496
Create Date: 2025-12-19 04:14:40.431191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3753f5789fc5'
down_revision: Union[str, Sequence[str], None] = '7b5ca7b8d496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook', sa.Enum('RESEND', name='emailwebhookenum'), nullable=False),
    sa.Column('webhook_event_type', sa.Enum('EMAIL_RECEIVED', name='emailwebhookeventtypeenum'), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('attachment_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email_subject', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('email_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_to', sa.JSON(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('s3_type', sa.Enum('AMAZON_S3', 'ALIYUN_OSS', name='s3typeenum'), nullable=False),
    sa.Column('s3_region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_attachment')
    # ### end Alembic commands ###
