"""Initial migration.

Revision ID: 6fba3dc83d75
Revises: 
Create Date: 2025-12-30 09:39:39.620277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fba3dc83d75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook', postgresql.ENUM('RESEND', name='emailwebhookenum', create_type=False), nullable=False),
    sa.Column('webhook_event_type', postgresql.ENUM('EMAIL_RECEIVED', name='emailwebhookeventtypeenum', create_type=False), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('attachment_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email_subject', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('email_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_to', sa.JSON(), nullable=True),
    sa.Column('attachment_filename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('s3_type', postgresql.ENUM('AMAZON_S3', 'ALIYUN_OSS', name='s3typeenum', create_type=False), nullable=False),
    sa.Column('s3_region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_demo')
    op.drop_table('email_attachment')
    # ### end Alembic commands ###
