"""Add file_name field into EmailAttachment.

Revision ID: bdd4bf1897cb
Revises: 6fba3dc83d75
Create Date: 2025-12-30 09:44:34.524256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdd4bf1897cb'
down_revision: Union[str, Sequence[str], None] = '6fba3dc83d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_attachment', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False))
    op.create_unique_constraint(None, 'email_attachment', ['attachment_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_attachment', type_='unique')
    op.drop_column('email_attachment', 'file_name')
    # ### end Alembic commands ###
